# Generated by Django 5.2.17 on 2026-10-07 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='capacity',
            field=models.PositiveIntegerField(default=180, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
