# Generated by Django 5.2.17 on 2026-09-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='seat_class',
            field=models.CharField(choices=[('ECONOMY', 'Економ'), ('BUSINESS', 'Бізнес'), ('FIRST', 'Перший клас')], default='ECONOMY', max_length=20),
        ),
    ]
