# Generated by Django 5.2.17 on 2026-10-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0001_initial'),
        ('seats', '0002_seat_seat_class'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('airplane', 'number'), name='unique_seats_in_airplane'),
        ),
    ]
